[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "python-stk"
version = "0.4"
description = "Toolkit for 3D volume processing"
readme = "README.md"
license-files = ["LICENSE"]
authors = [
    { name = "Simon Ekström" },
]
dependencies = [
    "numpy",
]
